### ISSUE TITLE
Mismatch when reading mcycle CSR

### ISSUE THREAD

**Issue by taichi-ishitani** [tenstorrent/cosim-arch-checker#2]
Hi,

I'm integrating `cosim-arch-checker` with my TB to do cosim.
When I'm executing the `dhrystone` test on my RISCV core I get the following mismatch.

```
<752> DutGprWr: [Hart=0, Reg=X14, Data=0x2e1]
<752> DutRetire: [Hart=0, InstrTag=0x0 (0,0), PC=0x800029ac, Opcode=0xb0002773]
<752> Whisper Step #358: [Hart=0, InstrTag=0x0, ChangeCount=1, PC=0x800029ac, Opcode=0xb0002773, csrrs    x14, mcycle, x0]
<752> Whisper Step #358: [Hart=0, InstrTag=0x0, Resource=r, Addr=0xe, Data=0x166]
Register Mismatch
Step: 358
                 X14                     DUT:[Data:00000000000002e1]
                                         SIM:[Data:0000000000000166]
                  PC                     DUT:[Data:00000000800029ac]
                                         SIM:[Data:00000000800029ac]
Error: Core Arch Checker Mismatc
```

I think that mismatch between `mcycle` value of my RISCV core and the Whisper ISS causes this error.
How can I adjust `mcycle` value of the Whisper ISS?

**Comment by roosnam** [comment]
You can use a testbench option: `+arch_checks_instr_exclude=mcycle`

It adjusts the Whisper values to match DUT using the whisperPoke API.

**Comment by taichi-ishitani** [comment]
Thank you, @roosnam !
I will try it.
